### ISSUE TITLE
missing players in history

### ISSUE THREAD

**Issue by Aigul9** [Zamiell/hanabi-live#1163]
show history of friends -> other players
this column shows 1 player less than it actually was. if they are sorted alphabetically, then the last player is missing

**Comment by Zamiell** [comment]
should be fixed after next server restart, reopen issue if not

**Comment by padiwik** [comment]
Not fixed, the Players column in Friends history is still missing the last player

**Comment by Zamiell** [comment]
fixed now
