### ISSUE TITLE
Character Traits or 6 suits (rainbow) have been ending the game incorrectly

### ISSUE THREAD

**Issue by Str8AWay** [Zamiell/hanabi-live#341]
The game ended with a loss with no strikes and no reason for it to end due to traits.

id: 20117, seed: p4v3s13

Traits:
str8away - Stubborn
klapbot - Insistent
ninjasquirrel21 - contrarian
squirreliche - compulsive

It ended after str8away played a card. The previous player (squirreliche) had clued so that shouldn't have been a problem. Klapbot the next player had only clued once and the card he clued was played immediately after that, so that shouldn't have been a problem either.

<img width="1637" alt="screen shot 2019-02-15 at 9 35 19 am" src="https://user-images.githubusercontent.com/3453432/52866836-27922f00-3105-11e9-884f-de36e4fc3eb5.png">

We also had this problem the previous time we played with traits where we thought it ended for no reason, but I don't remember the details of that game.

**Comment by Str8AWay** [comment]
It happened again on a no character traits game. It might be the variant. Game ID: #20118

**Comment by Zamiell** [comment]
oh it probably has something to do with this commit that i did 21 hours ago:
https://github.com/Zamiell/hanabi-live/commit/6ee5c74adf5bba6b5663b81662d1036863253233

**Comment by Zamiell** [comment]
oh i found the problem, i was making it equal to 0 instead of equal to -1

**Comment by Zamiell** [comment]
fixed now

**Comment by fpvandoorn** [comment]
It's not fixed: #20254 ended early for no reason, in a character game.

**Comment by Zamiell** [comment]
"for no reason"

It ended because you left Raz with 0 clues, who is an Insistent character, which means that you automatically lose the game by design if you leave that character at 0 clues under certain conditions.

I added an extra message to alert the players when this occurs to make it more obvious.

**Comment by fpvandoorn** [comment]
> under certain conditions

Can you elaborate on this. Raz has clued twice, touching y2, and then touching y2+y3. *All* of these cards have been played, so Raz is under no obligation to clue according to his character.

**Comment by Zamiell** [comment]
seed of game 20254 is p4v13s6

**Comment by Zamiell** [comment]
ugh debugging this is a nightmare because its a super old game, so the database isn't consistent
if it happens again, give me a more recent game ID where this bug happens and reopen

**Comment by TheDaniMan** [comment]
It's definitely not fixed yet: look at game 167930. I was left with 0 clues, but one card from every clue that I gave had been played.

**Comment by Zamiell** [comment]
fixed, i will close this after the next server restart

**Comment by Zamiell** [comment]
should be fixed now
