### ISSUE TITLE
brown null isn't aligned

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/hanabi-live#620]
look at brown 3

**Comment by hanabirnoob** [comment]
Brown 5 even overlaps. Were the symbols made bigger as they use unicode character and the brown color on symbols would be too thin otherwise?

**Comment by Zamiell** [comment]
should be fixed i think

**Comment by hanabirnoob** [comment]
https://i.imgtc.ws/UkyS4Oy.png

Seems that the issue remains for some. Could it be that I play/spectate in wrong web browser?

**Comment by Zamiell** [comment]
you are supposed to play in chrome
