### ISSUE TITLE
Card cycling doesn't work during hypothetical

### ISSUE THREAD

**Issue by SashaIr** [Zamiell/hanabi-live#950]
As per title.

**Comment by Zamiell** [comment]
should be fixed, reopen if it doesn't work

**Comment by NoAnni** [comment]
It seems to me that it still doesn't work, I don't know if I'm doing anything wrong.

**Comment by Zamiell** [comment]
try now

**Comment by NoAnni** [comment]
It works, thank you!
