### ISSUE TITLE
Restarting a game raises various errors

### ISSUE THREAD

**Issue by cmangin** [Zamiell/hanabi-live#993]
Steps to reproduce all the errors I could see:
- Start a game with a password.
- Also spectate.
- Terminate the game.
- Restart.
Before the latest update, I believe the behavior was to directly restart the game with the same players, and the spectators being put back as spectators.

What I observed now:
- From the point of view of the one that restarted: ![hanabi_03](https://user-images.githubusercontent.com/2060299/80850600-10adfe80-8c1d-11ea-8a9c-0d0b56aafb7c.png)
- From the point of view of the other player: 
![hanabi_04](https://user-images.githubusercontent.com/2060299/80850624-36d39e80-8c1d-11ea-80e5-4908b98eac79.png)
- From the point of view of the spectator: 
![hanabi_05](https://user-images.githubusercontent.com/2060299/80850651-523ea980-8c1d-11ea-9b4b-6a24caece71e.png)

Having a password or not does not really change much. Sometimes I got this error instead for the person that restarts the game:
![hanabi_06](https://user-images.githubusercontent.com/2060299/80850742-c11c0280-8c1d-11ea-85de-ef5a52ab7b07.png)
while the other two are put back in the main lobby.

**Comment by Zamiell** [comment]
found the bug

**Comment by Zamiell** [comment]
should be fixed now, reply if not

**Comment by cmangin** [comment]
I'm still getting a warning when I'm spectating and it restarts, but at least it puts me in the right table, so that's much better :D 
![hanabi_07](https://user-images.githubusercontent.com/2060299/80851591-ec552080-8c22-11ea-89d3-153515775833.png)

**Comment by Zamiell** [comment]
oh i think i see the problem

**Comment by Zamiell** [comment]
ok let me know if it still happens after the server restart in 30 mins
